import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:dotted_border/dotted_border.dart';
import '../../../../../core/providers/product_provider.dart';
import '../../../../../core/providers/user_provider.dart';
import '../../../../../core/models/user_model.dart';
import '../../../../../core/models/product_model.dart';

class OfficerAddProductPage extends ConsumerStatefulWidget {
  const OfficerAddProductPage({super.key});

  @override
  ConsumerState<OfficerAddProductPage> createState() => _OfficerAddProductPageState();
}

class _OfficerAddProductPageState extends ConsumerState<OfficerAddProductPage> {
  UserModel? _selectedFarmer;
  final _nameController = TextEditingController();
  final _categoryController = TextEditingController();
  final _quantityController = TextEditingController();
  final _priceController = TextEditingController();
  final _noteController = TextEditingController();
  bool _isLoading = false;

  @override
  void dispose() {
    _nameController.dispose();
    _categoryController.dispose();
    _quantityController.dispose();
    _priceController.dispose();
    _noteController.dispose();
    super.dispose();
  }

  Future<void> _submitProduct() async {
    if (_selectedFarmer == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please select a farmer')),
      );
      return;
    }
    if (_nameController.text.isEmpty ||
        _quantityController.text.isEmpty ||
        _priceController.text.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please fill all required fields')),
      );
      return;
    }

    setState(() {
      _isLoading = true;
    });

    try {
      final product = ProductModel(
        id: '', // Will be generated by Firestore
        farmerId: _selectedFarmer!.id,
        farmerName: _selectedFarmer!.name,
        name: _nameController.text,
        category: _categoryController.text.isNotEmpty ? _categoryController.text : 'Vegetables',
        quantity: double.tryParse(_quantityController.text) ?? 0.0,
        unit: 'kg',
        location: _selectedFarmer!.district ?? 'Unknown',
        description: _noteController.text,
        price: double.tryParse(_priceController.text) ?? 0.0,
        status: 'active', // Officer approved directly
        createdAt: DateTime.now(),
      );

      await ref.read(productControllerProvider.notifier).addProduct(product);

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Product submitted successfully!')),
        );
        Navigator.pop(context);
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Submission failed: $e')),
        );
      }
    } finally {
      if (mounted) {
        setState(() {
          _isLoading = false;
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final farmersAsync = ref.watch(farmersProvider);

    return Scaffold(
      backgroundColor: const Color(0xFFF9F9F9),
      appBar: AppBar(
        backgroundColor: const Color(0xFF8D5A36), // Brown
        elevation: 0,
        leading: IconButton(
          icon: Container(
            padding: const EdgeInsets.all(8),
            decoration: const BoxDecoration(
              color: Colors.white,
              shape: BoxShape.circle,
            ),
            child: const Icon(Icons.arrow_back, color: Colors.black, size: 16),
          ),
          onPressed: () => Navigator.pop(context),
        ),
        title: const Text(
          'Add Product for Farmer',
          style: TextStyle(color: Colors.white, fontSize: 16, fontWeight: FontWeight.w600),
        ),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(20.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text(
              'Select Farmer',
              style: TextStyle(fontSize: 13, color: Colors.black87),
            ),
            const SizedBox(height: 6),
            farmersAsync.when(
              data: (farmers) {
                return _buildFarmerDropdown(farmers);
              },
              loading: () => const CircularProgressIndicator(),
              error: (err, stack) => Text('Error loading farmers: $err'),
            ),
            const SizedBox(height: 20),
            
            _buildImageUploadBox(),
            const SizedBox(height: 20),
            
            const Text(
              'Product Name',
              style: TextStyle(fontSize: 13, color: Colors.black87),
            ),
            const SizedBox(height: 6),
            _buildTextField(
              controller: _nameController,
              hintText: 'e.g Organic Tomatoes',
              prefixIcon: Icons.grass,
            ),
            const SizedBox(height: 16),
            
            const Text(
              'Category',
              style: TextStyle(fontSize: 13, color: Colors.black87),
            ),
            const SizedBox(height: 6),
            _buildTextField(
              controller: _categoryController,
              hintText: 'Vegetables',
              prefixIcon: Icons.eco,
            ),
            const SizedBox(height: 16),
            
            Row(
              children: [
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const Text(
                        'Quantity (kg)',
                        style: TextStyle(fontSize: 13, color: Colors.black87),
                      ),
                      const SizedBox(height: 6),
                      _buildTextField(
                        controller: _quantityController,
                        hintText: 'e.g. 100',
                        keyboardType: TextInputType.number,
                      ),
                    ],
                  ),
                ),
                const SizedBox(width: 16),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const Text(
                        'Price (Rs/kg)',
                        style: TextStyle(fontSize: 13, color: Colors.black87),
                      ),
                      const SizedBox(height: 6),
                      _buildTextField(
                        controller: _priceController,
                        hintText: 'e.g. 120',
                        keyboardType: TextInputType.number,
                      ),
                    ],
                  ),
                ),
              ],
            ),
            const SizedBox(height: 16),
            
            const Text(
              'Location (GPS)',
              style: TextStyle(fontSize: 13, color: Colors.black87),
            ),
            const SizedBox(height: 6),
            _buildGpsButton(),
            const SizedBox(height: 16),
            
            const Text(
              'Officer note (optional)',
              style: TextStyle(fontSize: 13, color: Colors.black87),
            ),
            const SizedBox(height: 6),
            _buildTextField(
              controller: _noteController,
              hintText: 'Or enter location manually',
              maxLines: 2,
            ),
            const SizedBox(height: 32),
            
            SizedBox(
              width: double.infinity,
              child: ElevatedButton(
                onPressed: _isLoading ? null : _submitProduct,
                style: ElevatedButton.styleFrom(
                  backgroundColor: const Color(0xFF8D5A36),
                  padding: const EdgeInsets.symmetric(vertical: 16),
                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                ),
                child: _isLoading 
                  ? const SizedBox(width: 20, height: 20, child: CircularProgressIndicator(color: Colors.white, strokeWidth: 2))
                  : const Text(
                      'Submit on Behalf of Farmer',
                      style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold),
                    ),
              ),
            ),
            const SizedBox(height: 32),
          ],
        ),
      ),
    );
  }

  Widget _buildFarmerDropdown(List<UserModel> farmers) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 4),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: const Color(0xFF8D5A36), width: 1.2),
      ),
      child: DropdownButtonHideUnderline(
        child: DropdownButton<UserModel>(
          value: _selectedFarmer,
          isExpanded: true,
          hint: const Text('Select Farmer', style: TextStyle(color: Colors.black54, fontSize: 14)),
          icon: const Icon(Icons.arrow_drop_down, color: Colors.green),
          items: farmers.map((UserModel farmer) {
            return DropdownMenuItem<UserModel>(
              value: farmer,
              child: Row(
                children: [
                  Container(
                    width: 32,
                    height: 32,
                    decoration: const BoxDecoration(
                      color: Color(0xFFC5E1A5),
                      shape: BoxShape.circle,
                    ),
                    alignment: Alignment.center,
                    child: const Text('🧑‍🌾', style: TextStyle(fontSize: 14)),
                  ),
                  const SizedBox(width: 12),
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        Text(
                          farmer.name,
                          style: const TextStyle(fontSize: 13, fontWeight: FontWeight.bold),
                        ),
                        Text(
                          '${farmer.district ?? 'No District'} - ${farmer.status == 'approved' ? 'Verified' : 'Pending'}',
                          style: const TextStyle(fontSize: 10, color: Colors.black54),
                        ),
                      ],
                    ),
                  ),
                ],
              ),
            );
          }).toList(),
          onChanged: (UserModel? val) {
            setState(() {
              _selectedFarmer = val;
            });
          },
        ),
      ),
    );
  }

  Widget _buildImageUploadBox() {
    return DottedBorder(
      options: RoundedRectDottedBorderOptions(
        color: Colors.green,
        strokeWidth: 1,
        dashPattern: const [6, 4],
        radius: const Radius.circular(12),
      ),
      child: Container(
        width: double.infinity,
        padding: const EdgeInsets.symmetric(vertical: 36),
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.circular(12),
        ),
        child: const Column(
          children: [
            Icon(Icons.image_outlined, color: Colors.black54, size: 36),
            SizedBox(height: 8),
            Text(
              'Tap to upload product photo',
              style: TextStyle(color: Colors.black87, fontWeight: FontWeight.bold, fontSize: 13),
            ),
            SizedBox(height: 4),
            Text(
              'JPG, PNG up to 5MB',
              style: TextStyle(color: Colors.grey, fontSize: 11),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildTextField({
    required TextEditingController controller,
    required String hintText,
    IconData? prefixIcon,
    TextInputType keyboardType = TextInputType.text,
    int maxLines = 1,
  }) {
    return Container(
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(8),
        border: Border.all(color: Colors.grey.shade300),
      ),
      child: TextField(
        controller: controller,
        keyboardType: keyboardType,
        maxLines: maxLines,
        style: const TextStyle(fontSize: 14),
        decoration: InputDecoration(
          hintText: hintText,
          hintStyle: TextStyle(color: Colors.grey.shade400, fontSize: 13),
          prefixIcon: prefixIcon != null ? Icon(prefixIcon, color: Colors.green, size: 18) : null,
          border: InputBorder.none,
          contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
        ),
      ),
    );
  }

  Widget _buildGpsButton() {
    return GestureDetector(
      onTap: () {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('GPS Location fetched! (Mock)')),
        );
      },
      child: DottedBorder(
        options: RoundedRectDottedBorderOptions(
          color: Colors.green,
          strokeWidth: 1,
          dashPattern: const [6, 4],
          radius: const Radius.circular(8),
        ),
        child: Container(
          width: double.infinity,
          padding: const EdgeInsets.symmetric(vertical: 24),
          decoration: BoxDecoration(
            color: const Color(0xFFF1F8E9),
            borderRadius: BorderRadius.circular(8),
          ),
          child: const Column(
            children: [
              Icon(Icons.location_on, color: Colors.black87, size: 28),
              SizedBox(height: 8),
              Text(
                'Use Current Location',
                style: TextStyle(color: Colors.black87, fontWeight: FontWeight.bold, fontSize: 13),
              ),
              SizedBox(height: 4),
              Text(
                'Tap to enable GPS',
                style: TextStyle(color: Colors.green, fontSize: 11),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
